/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package checkout;

import javax.swing.JFrame;

import wom.MainWindow;

/**
 * 
 * @author thanh
 */
public class AskForCheckOut extends javax.swing.JFrame {

	/**
	 * Creates new form AskForCheckOut
	 */
	public AskForCheckOut() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		continueShoppingButton = new javax.swing.JButton();
		continueCheckOutButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("You want to check out?");

		continueShoppingButton.setText("Continue shopping");
		continueShoppingButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						continueShoppingButtonActionPerformed(evt);
					}
				});

		continueCheckOutButton.setText("Checkout");
		continueCheckOutButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						continueCheckOutButtonActionPerformed(evt);
					}
				});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(39, 39, 39)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(
														jLabel1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														140,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														continueShoppingButton))
								.addGap(46, 46, 46)
								.addComponent(continueCheckOutButton,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										129,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(62, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(34, 34, 34)
								.addComponent(jLabel1)
								.addGap(38, 38, 38)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														continueShoppingButton,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														37,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														continueCheckOutButton,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														37,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(33, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void continueShoppingButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_continueShoppingButtonActionPerformed
		// TODO add your handling code here:
		setVisible(false);
		dispose();
	}// GEN-LAST:event_continueShoppingButtonActionPerformed

	private void continueCheckOutButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_continueCheckOutButtonActionPerformed
		// TODO add your handling code here:
		JFrame jf = new CheckoutFrame(MainWindow.cartClick);
		jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
		jf.setVisible(true);
		setVisible(false);
		dispose();
	}// GEN-LAST:event_continueCheckOutButtonActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AskForCheckOut.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AskForCheckOut.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AskForCheckOut.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AskForCheckOut.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AskForCheckOut().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton continueCheckOutButton;
	private javax.swing.JButton continueShoppingButton;
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables
}
