/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package checkout;

import java.awt.event.ActionEvent;
import java.io.IOException;
import java.util.ArrayList;

import javax.swing.JOptionPane;

import jxl.write.WriteException;

import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.criterion.Disjunction;
import org.hibernate.criterion.Restrictions;

import wom.MainWindow;
import bill.BillElement;
import bill.WriteExcel;

import databasemanager.CartElement;
import databasemanager.Disk;
import databasemanager.VipMember;

import admin.DAO.HibernateUtil;

/**
 * 
 * @author thanh
 */
public class InputVipMemberId1 extends javax.swing.JFrame {

	/**
	 * Creates new form InputVipMemberId
	 * 
	 * @param billElementList
	 */
	ArrayList<BillElement> billElementList;

	public InputVipMemberId1(ArrayList<BillElement> billElementList) {
		initComponents();
		this.billElementList = new ArrayList<BillElement>();
		this.billElementList = billElementList;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("YourVipId");

		jLabel2.setText("Your Name");

		jLabel3.setText("Please insert the right information");

		jLabel4.setText("Your email");

		jButton1.setText("OK");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton1ActionPerformed(evt);
				} catch (WriteException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jButton2.setText("Cancel");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap(
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		jButton1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		63,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(25, 25,
																		25)
																.addComponent(
																		jButton2))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(25, 25,
																		25)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						jLabel1)
																				.addComponent(
																						jLabel4))
																.addGap(32, 32,
																		32)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jTextField1)
																				.addComponent(
																						jTextField2)
																				.addComponent(
																						jTextField3,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						140,
																						Short.MAX_VALUE))))
								.addGap(53, 53, 53))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(47, 47, 47)
								.addComponent(jLabel3,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										179,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(94, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(16, 16, 16)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														jTextField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														jTextField2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4)
												.addComponent(
														jTextField3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addComponent(jLabel3)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										26, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton1)
												.addComponent(jButton2))
								.addGap(24, 24, 24)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	protected void jButton2ActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void jButton1ActionPerformed(ActionEvent evt)
			throws WriteException, IOException {
		// TODO Auto-generated method stub
		String id = jTextField1.getText();
		String name = jTextField2.getText();
		String email = jTextField3.getText();
		String message = "";
		if (id == null || id.equals("")) {
			message = message + "Id field must not be empty\n";
		}
		if (name == null || name.equals("")) {
			message = message + "Name field must not be empty\n";
		}
		if (email == null || email.equals("")) {
			message = message + "Message field must not be empty\n";
		}
		if (!message.equals("")) {
			JOptionPane.showMessageDialog(null, message);
		} else {
			HibernateUtil hu = new HibernateUtil();
			SessionFactory sf = hu.getSessionFactory();
			Session session = sf.openSession();
			Criteria criteria = session.createCriteria(VipMember.class);
			criteria.add(Restrictions.eq("id", id));
			criteria.add(Restrictions.eq("name", name));
			criteria.add(Restrictions.eq("email", email));
			VipMember vipMember = (VipMember) criteria.uniqueResult();
			session.beginTransaction().commit();
			session.close();
			if (vipMember == null) {
				JOptionPane.showMessageDialog(null,
						"You are not vip member. You can not check out");
				setVisible(false);
				dispose();
			} else {

				WriteExcel we = new WriteExcel(billElementList);
				we.setOutputFile("d:/bill.xls");
				we.write();
				JOptionPane.showMessageDialog(null, "Check out complete");
				setVisible(false);
				dispose();
				ArrayList<CartElement> cartElementList = MainWindow.cartClick
						.getCp().getCartElementList();
				ArrayList<Disk> diskDatabase = new ArrayList<Disk>();
				session = sf.openSession();
				criteria = session.createCriteria(Disk.class);
				Disjunction or = Restrictions.disjunction();
				for (int i = 0; i < cartElementList.size(); i++) {
					or.add(Restrictions.eq("filmId", cartElementList.get(i)
							.getFilmId()));
				}
				criteria.add(or);
				diskDatabase = (ArrayList<Disk>) criteria.list();
				int totalAmount;
				for (int i = 0; i < diskDatabase.size(); i++) {
					totalAmount = Integer.parseInt(diskDatabase.get(i)
							.getTotalAmount())
							- cartElementList.get(i).getDiskAmount();
					if (totalAmount > 0) {
						diskDatabase.get(i).setTotalAmount(totalAmount + "");
					} else {
						diskDatabase.get(i).setTotalAmount("0");
					}
					session.saveOrUpdate(diskDatabase.get(i));
				}

				session.beginTransaction().commit();
				session.close();
			}

		}

	}

	/**
	 * @param args
	 *            the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	// End of variables declaration//GEN-END:variables
}
