/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cart;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;

import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

import admin.DAO.HibernateUtil;

import databasemanager.CartElement;

/**
 * 
 * @author thanh
 */
public class CartPanel extends javax.swing.JPanel {
	private ArrayList<CartElement> cartElementList;
	private javax.swing.JButton viewCartButton;

	/**
	 * Creates new form CartPanel
	 * 
	 * @throws FileNotFoundException
	 */
	public CartPanel()  {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * 
	 * @throws FileNotFoundException
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()  {
		// Insets insets = getInsets();
		//
		// Dimension d;
		CartElementPanel tmp;
		setBackground(Color.white);

		setCartElementList();
		setLayout(new GridLayout(cartElementList.size(), 1));
		for (int i = cartElementList.size()-1; i >= 0; i--) {
			tmp = new CartElementPanel(cartElementList.get(i));
			// d = tmp.getPreferredSize();
			// tmp.setBounds(insets.left, (int) (insets.top + i *
			// d.getHeight()),
			// (int) d.getWidth(), (int) d.getHeight());
			add(tmp);

		}

	}// </editor-fold>//GEN-END:initComponents

	public void setCartElementList() {
		CartElement ce;
		String tmp;
		String[] ceString;
		cartElementList = new ArrayList<CartElement>();
		JButton viewShoppingCart = new JButton();
		HibernateUtil hu = new HibernateUtil();
		SessionFactory sf = hu.getSessionFactory();
		Session session = sf.openSession();
		// setLayout(new GridLayout(cartElementList.size(), 1));
		Criteria criteria = session.createCriteria(CartElement.class);
		cartElementList = (ArrayList<CartElement>) criteria.list();
		session.beginTransaction().commit();
		
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;

	// End of variables declaration//GEN-END:variables

	public static void main(String[] args) throws FileNotFoundException {
		JFrame jf = new JFrame();
		CartPanel cp = new CartPanel();
		JScrollPane jsp = new JScrollPane(cp,
				ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS,
				ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

		jf.add(jsp);

		jf.setSize(250, 80 * cp.getCartElementList().size());

		jf.setLocation(1090, 70);
		jf.setVisible(true);
	}

	public ArrayList<CartElement> getCartElementList() {
		return cartElementList;
	}
}
