/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fullcart;

import java.awt.Color;
import java.awt.GridLayout;

import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.criterion.Restrictions;

import admin.DAO.HibernateUtil;

import databasemanager.CartElement;
import databasemanager.Disk;
import databasemanager.MoneyUnit;
import databasemanager.Movie;

import moviedisplaypanel.ImageLabel;

/**
 * 
 * @author thanh
 */
public class FullCartElement extends javax.swing.JPanel {

	/**
	 * Creates new form FullCartTitle
	 */
	public FullCartElement(CartElement ce) {
		initComponents(ce);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents(CartElement ce) {
		setLayout(new GridLayout(1, 6));
		setBackground(Color.white);
		imageLabel = new javax.swing.JLabel();
		filmNameLabel = new javax.swing.JLabel("",JLabel.CENTER);
		sizeLabel = new javax.swing.JLabel("",JLabel.CENTER);
		quantityLabel = new javax.swing.JLabel("",JLabel.CENTER);
		amountLabel = new javax.swing.JLabel("",JLabel.CENTER);
		deleteLabel = new javax.swing.JLabel("",JLabel.CENTER);
		plusAmountLabel = new javax.swing.JLabel("",JLabel.CENTER);
		minusAmountLabel = new javax.swing.JLabel("",JLabel.CENTER);
		Movie movie = new Movie();
		Disk disk = new Disk();
		HibernateUtil hu = new HibernateUtil();
		SessionFactory sf = hu.getSessionFactory();
		Session session = sf.openSession();
		Criteria movieCriteria = session.createCriteria(Movie.class);
		Criteria diskCriteria = session.createCriteria(Disk.class);
		Criteria moneyUnitCriteria = session.createCriteria(MoneyUnit.class);
		MoneyUnit mu = (MoneyUnit) moneyUnitCriteria.uniqueResult();
		movieCriteria.add(Restrictions.eq("id", ce.getFilmId()));
		diskCriteria.add(Restrictions.eq("id", ce.getFilmId()));
		movie = (Movie) movieCriteria.uniqueResult();
		disk = (Disk) diskCriteria.uniqueResult();
		session.beginTransaction().commit();
		// IMAGE
		ImageLabel tmpImageLabel = new ImageLabel("data/Films/"
				+ ce.getFilmId() + "/0.jpg", 42, 63);
		imageLabel = tmpImageLabel;
	
		// FILM NAME
		filmNameLabel.setText(movie.getName());

		sizeLabel.setText(disk.getDiskPerMovie() + " disk(s)");

		quantityLabel.setText(ce.getDiskAmount() + "");

		amountLabel.setText(Integer.parseInt(disk.getDiskPerMovie())
				* ce.getDiskAmount() * mu.getUsd() + " USD");

		deleteLabel.setText("  x  ");

		plusAmountLabel.setText("+");

		minusAmountLabel.setText("-");
		add(imageLabel);
		add(filmNameLabel);
		add(sizeLabel);
		add(quantityLabel);
		add(amountLabel);
		add(deleteLabel);

	}// </editor-fold>//GEN-END:initComponents
		// Variables declaration - do not modify//GEN-BEGIN:variables

	private javax.swing.JLabel amountLabel;
	private javax.swing.JLabel deleteLabel;
	private javax.swing.JLabel filmNameLabel;
	private javax.swing.JLabel imageLabel;
	private javax.swing.JLabel minusAmountLabel;
	private javax.swing.JLabel plusAmountLabel;
	private javax.swing.JLabel quantityLabel;
	private javax.swing.JLabel sizeLabel;

	// End of variables declaration//GEN-END:variables
	public static void main(String[] args) {
		JFrame jf = new JFrame();
		CartElement ce = new CartElement();
		ce.setDiskAmount(3);
		ce.setFilmId("1179034");
		jf.setSize(900, 280);
		jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		JPanel tmp = new JPanel();
		tmp.add(new FullCartTitle());
		tmp.add(new FullCartElement(ce));
		tmp.setLayout(new GridLayout(3, 6));
		tmp.setBorder(BorderFactory.createTitledBorder(" Cart "));
		ce.setDiskAmount(3);
		ce.setFilmId("1190080");
		tmp.add(new FullCartElement(ce));
		jf.add(tmp);
		jf.setVisible(true);

	}
}
