/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fullcart;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;

import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 * 
 * @author thanh
 */
public class FullCartTitle extends javax.swing.JPanel {

	/**
	 * Creates new form FullCartTitle
	 */
	public FullCartTitle() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		setBackground(Color.white);
		jLabel1 = new javax.swing.JLabel("",JLabel.CENTER);
		jLabel2 = new javax.swing.JLabel("",JLabel.CENTER);
		jLabel3 = new javax.swing.JLabel("",JLabel.CENTER);
		jLabel5 = new javax.swing.JLabel("",JLabel.CENTER);
		jLabel6 = new javax.swing.JLabel("",JLabel.CENTER);
		jLabel7 = new javax.swing.JLabel("",JLabel.CENTER);
		jLabel8 = new javax.swing.JLabel("",JLabel.CENTER);
		setLayout(new GridLayout(1, 6));
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("SHOPPING CART");
		jLabel1.setFont(Font.decode("arial, clean, sans-serif-BOLD-20"));
		jLabel2.setText("IMAGE");
		jLabel2.setFont(Font.decode("arial, clean, sans-serif-BOLD-13"));
		jLabel3.setText("FILM NAME");
		jLabel3.setFont(Font.decode("arial, clean, sans-serif-BOLD-13"));
		jLabel5.setText("SIZE");
		jLabel5.setFont(Font.decode("arial, clean, sans-serif-BOLD-13"));
		jLabel6.setText("QUANTITY");
		jLabel6.setFont(Font.decode("arial, clean, sans-serif-BOLD-13"));
		jLabel7.setText("AMOUNT");
		jLabel7.setFont(Font.decode("arial, clean, sans-serif-BOLD-13"));
		jLabel8.setText("DELETE");
		jLabel8.setFont(Font.decode("arial, clean, sans-serif-BOLD-13"));
		
		add(jLabel2);
		add(jLabel3);
		add(jLabel5);
		add(jLabel6);
		add(jLabel7);
		add(jLabel8);

	}// </editor-fold>//GEN-END:initComponents
		// Variables declaration - do not modify//GEN-BEGIN:variables

	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;

	// End of variables declaration//GEN-END:variables
	public static void main(String[] args) {
		JFrame jf = new JFrame();
		jf.setSize(900, 140);
		jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		jf.add(new FullCartTitle());
		jf.setVisible(true);
	}
}
