/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddNewAdmin.java
 *
 * Created on Oct 27, 2011, 12:27:38 AM
 */
package admin.view;

import java.awt.Image;
import java.util.Calendar;

import javax.swing.text.JTextComponent;

import admin.controller.PersonController;

/**
 *
 * @author CodeBlue
 */
public class AddNewPerson extends javax.swing.JDialog {

    /** Creates new form AddNewPerson */
    public AddNewPerson() {
        super();
        initComponents();
        Image icon = getToolkit().getImage(getClass().getResource("/images/app_icon_32.png"));
        setIconImage(icon);
        setLocation(250, 100);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        
        jPanel1 = new javax.swing.JPanel();
        
        jLabelName = new javax.swing.JLabel();
        jLabelGender = new javax.swing.JLabel();
        jLabelBirthday = new javax.swing.JLabel();
        jLabelStar = new javax.swing.JLabel();
        jLabelDirector = new javax.swing.JLabel();
        jLabelBorn = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelJob = new javax.swing.JLabel();
        
        txtDirector = new javax.swing.JTextField();
        txtBorn = new javax.swing.JTextField();
        txtPName = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtStar = new javax.swing.JTextField();
        
        radMale = new javax.swing.JRadioButton();
        radFemale = new javax.swing.JRadioButton();
        
        isStar = new javax.swing.JCheckBox();
        isDirector = new javax.swing.JCheckBox();
        
        jxDate = new org.jdesktop.swingx.JXDatePicker();
        
        btnInsert = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Person");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(51, 51, 51));
        jLabelName.setText("Name");

        jLabelGender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelGender.setForeground(new java.awt.Color(51, 51, 51));
        jLabelGender.setText("Gender");

        jLabelBirthday.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelBirthday.setForeground(new java.awt.Color(51, 51, 51));
        jLabelBirthday.setText("Birthday");

        jLabelStar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelStar.setForeground(new java.awt.Color(51, 51, 51));
        jLabelStar.setText("Star");

        jLabelDirector.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDirector.setForeground(new java.awt.Color(51, 51, 51));
        jLabelDirector.setText("Director");

        jLabelBorn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelBorn.setForeground(new java.awt.Color(51, 51, 51));
        jLabelBorn.setText("Born");
        
        jLabelJob.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelJob.setForeground(new java.awt.Color(51, 51, 51));
        jLabelJob.setText("Job");

        txtDirector.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        radMale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radMale);
        radMale.setSelected(true);
        radMale.setText("Male");

        radFemale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radFemale);
        radFemale.setText("Female");
        
        isStar.setBackground(new java.awt.Color(255, 255, 255));
        isStar.setText("Star");
        isStar.setFocusable(false);

        isDirector.setBackground(new java.awt.Color(255, 255, 255));
        isDirector.setText("Director");
        isDirector.setFocusable(false);

        txtBorn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtPName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Add New Person");

        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.setMargin(new java.awt.Insets(2, 9, 2, 9));
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/no.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setMargin(new java.awt.Insets(2, 9, 2, 9));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabelId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelId.setForeground(new java.awt.Color(51, 51, 51));
        jLabelId.setText("Id");

        txtStar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelId)
                    .addComponent(jLabelName)
                    .addComponent(jLabelGender)
                    .addComponent(jLabelBirthday)
                    .addComponent(jLabelJob)
                    .addComponent(jLabelBorn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
              			.addComponent(isStar)
               			.addComponent(isDirector))
                	.addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radMale)
                        .addComponent(radFemale))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtId)
                        .addComponent(txtPName, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jxDate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBorn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnInsert)
                .addGap(74, 74, 74)
                .addComponent(btnCancel)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(txtPName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radMale)
                        .addComponent(jLabelGender))
                    .addComponent(radFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBirthday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJob)
                    .addComponent(isStar)
                    .addComponent(isDirector))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBorn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBorn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInsert)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        // Validate text field
        JTextComponent[] tcp = {txtId, txtPName, txtBorn};
        if (!Validator.validateComponents(tcp)) {
            return;
        }
        // get values
        String id = txtId.getText();
        String name = txtPName.getText();
        String born = txtBorn.getText();
        String gender = "Male";
        boolean male = true;
        if (radFemale.isSelected()) {
            male = false;
            gender = "Female";
        }
        String star = "0";
        if (isStar.isSelected()) {
            star = "1";
        }
        String director = "0";
        if (isDirector.isSelected()) {
            director = "1";
        }
        String day = String.valueOf(jxDate.getDate().getDay());
        String month = String.valueOf(jxDate.getDate().getMonth()+1);
        String year = String.valueOf(jxDate.getDate().getYear()+1900);
        String day1 = day+"-"+month;
        // add
        if (PersonController.insert(id, name, gender, day1, year, born, director, star)) {
            new CustomMessageDialog(null, true, "Done!", "Added a new person sucessfully!", CustomMessageDialog.DONE);
            // reload table after insert
            AdminPersonList.reloadTable();
            // highlight the inserted row
            int count = AdminMovieList2.jxTable.getRowCount();
            AdminPersonList.jxTable.changeSelection(count - 1, count - 1, false, false);            //
            dispose();
        }
    }//GEN-LAST:event_btnInsertActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnInsert;
    
    private javax.swing.ButtonGroup buttonGroup1;
    
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelBirthday;
    private javax.swing.JLabel jLabelStar;
    private javax.swing.JLabel jLabelDirector;
    private javax.swing.JLabel jLabelBorn;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelJob;
    
    private javax.swing.JPanel jPanel1;
    
    private org.jdesktop.swingx.JXDatePicker jxDate;
    
    private javax.swing.JRadioButton radFemale;
    private javax.swing.JRadioButton radMale;
    
    private javax.swing.JCheckBox isStar;
    private javax.swing.JCheckBox isDirector;
    
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPName;
    private javax.swing.JTextField txtDirector;
    private javax.swing.JTextField txtBorn;
    private javax.swing.JTextField txtStar;
    // End of variables declaration//GEN-END:variables
}
