package admin.view;


import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.util.List;

import javax.swing.JPanel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

import databasemanager.DatabaseManager;
import databasemanager.Movie;

/**
 *
 * @author CodeBlue
 */
public class AdminMainFrame2 extends javax.swing.JFrame {

    private int x;
    private int y;
	private DatabaseManager database = new DatabaseManager();

    /** Creates new form PersonManagement */
    public AdminMainFrame2() {
        initComponents();
        Image icon = getToolkit().getImage(getClass().getResource("/images/app_icon_32.png"));
        setIconImage(icon);
        x = this.getWidth();
        y = this.getHeight();
        motion();
        setVisible(true);
    }

    private void motion() {
        this.setSize(0, 0);
        new Thread(new SizeMonitor(this, x, y)).start();
    }
	private List<Movie> movieList = database.getMovieList();
	private AdminMovieList adminMovieList = new AdminMovieList(movieList);
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JButton();
        btnPerson = new javax.swing.JButton();
        btnStatistics = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Film Management System");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(18, 97, 174));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/welcome.png"))); // NOI18N
        mainPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 660, 90));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/welcome_gif.gif"))); // NOI18N
        mainPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 610, 30));

        jPanel1.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 760, 450));

        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_admin_dark.png"))); // NOI18N
        btnAdmin.setToolTipText("Manage managers");
        btnAdmin.setBorder(null);
        btnAdmin.setContentAreaFilled(false);
        btnAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdmin.setFocusable(false);
        btnAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdminMouseExited(evt);
            }
        });
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 100, 50));

        btnPerson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_labor_dark.png"))); // NOI18N
        btnPerson.setToolTipText("Detail Persons's information");
        btnPerson.setBorder(null);
        btnPerson.setContentAreaFilled(false);
        btnPerson.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerson.setFocusable(false);
        btnPerson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPersonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPersonMouseExited(evt);
            }
        });
        btnPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonActionPerformed(evt);
            }
        });
        jPanel1.add(btnPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 100, 50));
        
        btnStatistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_admin_dark.png"))); // NOI18N
        btnStatistics.setToolTipText("Manage managers");
        btnStatistics.setBorder(null);
        btnStatistics.setContentAreaFilled(false);
        btnStatistics.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStatistics.setFocusable(false);
        btnStatistics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStatisticsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStatisticsMouseExited(evt);
            }
        });
        btnStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticsActionPerformed(evt);
            }
        });
        jPanel1.add(btnStatistics, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 100, 50));
        
        jMenu1.setText("File");

        mnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit_16.png"))); // NOI18N
        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/label_top.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 110));
        jMenu1.add(mnExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold defaultstate="collapsed" desc="main buttons click events">

    protected void btnStatisticsActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
        personActive = false;
        adminActive = false;
        statisticsActive = true;
        btnPerson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_labor_dark.png")));
        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_admin_dark.png")));
        btnStatistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_admin_white.png")));
        callJPanel(statisticsControl);
	}

	protected void btnStatisticsMouseExited(MouseEvent evt) {
		// TODO Auto-generated method stub
        if (!statisticsActive) {
            btnStatistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_admin_dark.png")));
        }
	}

	protected void btnStatisticsMouseEntered(MouseEvent evt) {
		// TODO Auto-generated method stub
        if (!statisticsActive) {
            btnStatistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_admin_dark.png")));
        }
	}

	private void btnPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonActionPerformed
        // TODO add your handling code here:
        personActive = true;
        adminActive = false;
        statisticsActive = false;
        btnPerson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_labor_white.png")));
        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_admin_dark.png")));
        btnStatistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_admin_dark.png")));
        callJPanel(personControl);
    }

    private void btnPersonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonMouseEntered
        // TODO add your handling code here:
        if (!personActive) {
            btnPerson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_labor_hover.png")));
        }
    }

    private void btnPersonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonMouseExited
        // TODO add your handling code here:
        if (!personActive) {
            btnPerson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_labor_dark.png")));
        }
    }
    
    // if ManageManager is clicked
    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        adminActive = true;
        personActive = false;
        statisticsActive = false;
        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_admin_white.png")));
        btnPerson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_labor_dark.png")));
        btnStatistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_admin_dark.png")));
        callJPanel(adminControl);
    }//GEN-LAST:event_btnAdminActionPerformed
    //</editor-fold>

    // Admin button on hover
    private void btnAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminMouseEntered
        // TODO add your handling code here:
        if (!adminActive) {
            btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_admin_hover.png")));
        }
    }//GEN-LAST:event_btnAdminMouseEntered

    // Admin button mouse exit
    private void btnAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminMouseExited
        // TODO add your handling code here:
        if (!adminActive) {
            btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_admin_dark.png")));
        }
    }//GEN-LAST:event_btnAdminMouseExited

    //<editor-fold defaultstate="collapsed" desc="toolbar events on click">
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        new CustomMessageDialog(this, true, "Confirm Message", "Are you sure to exit?", CustomMessageDialog.CONFIRM);
        if (CustomMessageDialog.STATUS == CustomMessageDialog.CANCEL) {
            return;
        }
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        new CustomMessageDialog(this, true, "Confirm Message", "Are you sure to exit?", CustomMessageDialog.CONFIRM);
        if (CustomMessageDialog.STATUS == CustomMessageDialog.CANCEL) {
            return;
        }
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        // TODO add your handling code here:
        btnExitActionPerformed(evt);
    }//GEN-LAST:event_mnExitActionPerformed

    // Method to call any panel into main frame
    private void callJPanel(JPanel jpanel) {
        mainPanel.removeAll();
        jpanel.setVisible(false);
        mainPanel.add(jpanel, new AbsoluteConstraints(0, 0, mainPanel.getWidth(), mainPanel.getHeight()));
        jpanel.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
               // SplashScreen splash = new SplashScreen();
                //splash.showSplash();
            }
        });
    }

    public static boolean adminActive = false;
    public static boolean personActive = false;
    public static boolean statisticsActive = false;
    AdminControl adminControl = new AdminControl();
    PersonControl personControl = new PersonControl();
    StatisticsControl statisticsControl = new StatisticsControl();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnPerson;
    private javax.swing.JButton btnStatistics;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem mnExit;
    
    // End of variables declaration//GEN-END:variables
}

