/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hotmovie;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

import javax.swing.Timer;

import moviedisplaypanel.ImageLabel;

import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.criterion.Restrictions;

import databasemanager.Movie;

import admin.DAO.HibernateUtil;

/**
 * 
 * @author thanh
 */
public class HotMovieElementPanel extends javax.swing.JPanel {
	private javax.swing.JLabel imageHotFilmLabel;
	private javax.swing.JLabel nameHotFilmLabel;
	private Timer timer;
	private String id;
	/**
	 * Creates new form HotMovieElementPanel
	 */

	public HotMovieElementPanel(Timer timer, String id) {
		initComponents(id);
		this.id = id;
		this.timer = timer;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents(String id) {
		HibernateUtil hu = new HibernateUtil();
		SessionFactory sf = hu.getSessionFactory();
		Session session = sf.openSession();
		Criteria criteria = session.createCriteria(Movie.class);
		criteria.add(Restrictions.eq("id", id));
		Movie movie = (Movie) criteria.uniqueResult();
		session.close();
		if (movie != null) {
			ImageLabel tmp = new ImageLabel("data/Films/" + movie.getId()
					+ "/0.jpg", 95, 95);
			imageHotFilmLabel = new javax.swing.JLabel();
			nameHotFilmLabel = new javax.swing.JLabel();

			imageHotFilmLabel = tmp;

			nameHotFilmLabel.setText(movie.getName());

			javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
			this.setLayout(layout);
			layout.setHorizontalGroup(layout
					.createParallelGroup(
							javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(
							layout.createSequentialGroup()
									.addContainerGap()
									.addComponent(
											imageHotFilmLabel,
											javax.swing.GroupLayout.PREFERRED_SIZE,
											87,
											javax.swing.GroupLayout.PREFERRED_SIZE)
									.addGap(18, 18, 18)
									.addComponent(
											nameHotFilmLabel,
											javax.swing.GroupLayout.PREFERRED_SIZE,
											100,
											javax.swing.GroupLayout.PREFERRED_SIZE)
									.addContainerGap(26, Short.MAX_VALUE)));
			layout.setVerticalGroup(layout
					.createParallelGroup(
							javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(
							layout.createSequentialGroup()
									.addContainerGap()
									.addComponent(
											imageHotFilmLabel,
											javax.swing.GroupLayout.DEFAULT_SIZE,
											javax.swing.GroupLayout.DEFAULT_SIZE,
											Short.MAX_VALUE).addContainerGap())
					.addGroup(
							layout.createSequentialGroup().addGap(19, 19, 19)
									.addComponent(nameHotFilmLabel)
									.addContainerGap(84, Short.MAX_VALUE)));
		}
	}// </editor-fold>//GEN-END:initComponents
		// Variables declaration - do not modify//GEN-BEGIN:variables

	// End of variables declaration//GEN-END:variables
}
